### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by maartenschalekamp** [puppetlabs/install-puppet#2]
## Describe the Bug
Currently the script does not include Ubuntu 22.04 in the case statement to determine the deb_codename.

## Expected Behavior
Include 22.04 codename in script

## Steps to Reproduce
Execute current script will try to download a file with no codename, which fails.

## Environment
 - Platform [Ubuntu 22.04]

**Comment by joshcooper** [comment]
Fixed in PR#6
